[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
onchain = "C4jFcBypYefdgw2goHbKREMjZSyRo4LknBVDP5cegYLN"

[provider]
cluster = "devnet"
wallet = "C:\\Users\\arche\\.config\\solana\\veztra-deploy.json"

[scripts]
test = "cargo test"

[hooks]
